#!/bin/bash
# 04-save.sh — stage 4 of 4: save
#
# USAGE:
#   ./04-save.sh
#
# REQUIREMENTS:
#   - bash, date
#   - 03-process.sh has already run and populated ./work/03-processed/
#
# WHAT IT DOES:
#   Aggregates every processed file into a single markdown digest at
#   ./output/digest-YYYY-MM-DD.md and prints the path. The aggregation is
#   intentionally dumb — it concatenates with headers. Smarter merging is
#   a separate job for a separate stage.
#
# INPUT:
#   ./work/03-processed/*.json
#
# OUTPUT:
#   ./output/digest-YYYY-MM-DD.md
#
# OWNS:    final artifact + naming
# HANDS OFF TO: nothing — this is the end of the pipeline

set -euo pipefail

IN_DIR="./work/03-processed"
OUT_DIR="./output"

if [ ! -d "$IN_DIR" ]; then
    echo "04-save: input dir not found: $IN_DIR (run 03-process.sh first)" >&2
    exit 1
fi

mkdir -p "$OUT_DIR"
TODAY="$(date +%Y-%m-%d)"
OUT_FILE="$OUT_DIR/digest-$TODAY.md"

{
    printf '# Beat digest — %s\n\n' "$TODAY"
    printf 'Generated by the pipeline scripts in `scripts/pipeline/`.\n\n'

    COUNT=0
    shopt -s nullglob
    for FILE in "$IN_DIR"/*.json; do
        BASE="$(basename "$FILE" .json)"
        printf '## %s\n\n' "$BASE"
        printf '```json\n'
        cat "$FILE"
        printf '\n```\n\n'
        COUNT=$((COUNT + 1))
    done

    if [ "$COUNT" -eq 0 ]; then
        printf '_No processed files found._\n'
    fi
} > "$OUT_FILE"

echo "04-save: wrote $OUT_FILE"
